const types = {
    hero: {
        GET_INITIAL_HERO: 'GET_INITIAL_HERO',
        SET_INITIAL_HERO: 'SET_INITIAL_HERO',
        GET_SEARCH_LIST: 'GET_SEARCH_LIST',
        SET_SEARCH_LIST: 'SET_SEARCH_LIST',
        GET_HERO_WITH_ID: 'GET_HERO_WITH_ID',
        CLEAR_CURRENT_HERO_OBJ: 'CLEAR_CURRENT_HERO_OBJ',
        GET_PUBLISHERS: "GET_PUBLISHERS",
        SET_PUBLISHER: "SET_PUBLISHER",
    },
    utils: {
        TOGGLE_IS_LOADING: 'TOGGLE_IS_LOADING',
        CLEAR_REDUX_SEARCH_LIST: 'CLEAR_REDUX_SEARCH_LIST'
    }
}

export default types